### ISSUE TITLE
SwampDragon 0.4.2 tests are failing

### ISSUE THREAD

**Issue by chokosabe** [jonashagstedt/swampdragon-notifications#2]
Is this still working after the update to swampdragon 0.4.2?

Local test seems to indicate not

Thanks.

**Comment by jonashagstedt** [comment]
Good spot! Will look at the tests right away

**Comment by chokosabe** [comment]
Hi Jonas, 

I upgraded all the libs and its not working fine again....
A bit difficult to match versions at the moment...

Thanks.

**Comment by jonashagstedt** [comment]
I've just pushed an update where the tests are fixed.
Nothing changed other than the tests so the package should work fine with latest (and previous version) of SD

**Comment by jonashagstedt** [comment]
I'll close this if it's all good now

**Comment by chokosabe** [comment]
Thats great thanks. Appreciate the help..
