### ISSUE TITLE
Add swampdragon and swapdragon_auth to requirements?

### ISSUE THREAD

**Issue by wengole** [jonashagstedt/swampdragon-notifications#4]
Just wondering why these are left out as they are required?

**Comment by jonashagstedt** [comment]
Good spot! I can't believe I missed that.
Fixed and committed

**Comment by wengole** [comment]
No worries. Loving your framework, followed the tutorial last night with angular, then discovered this, which is exactly what I want.

Willing to lend a hand if you need it
